services:
  jekyll:
    build: 
      context: tools
      target: jekyll
    profiles:
      - donotstart
  jekyll-serve:
    build: 
      context: tools
    volumes:
      - ./docs:/site
    ports:
      - '4000:4000'
